require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '9.0'

target 'garam_ios' do
  config = use_native_modules!
  
  # Pods for garam_ios
  pod 'Firebase/Core'
  pod 'Firebase/Messaging'

  use_react_native!(:path => config["reactNativePath"])
  

  pod 'react-native-webview', :path => '../node_modules/react-native-webview'

  target 'garam_iosTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
  end
end

target 'garam_ios-tvOS' do
  # Pods for garam_ios-tvOS

  target 'garam_ios-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end

